version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: medical-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.backend
    container_name: medical-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/medicaldb
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - CRYPTO_SECRET=${CRYPTO_SECRET}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.frontend
    container_name: medical-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: